baseURL = "https://orphicsec.com/"
languageCode = "en-us"
title = "O R P H I C"
theme = "PaperMod"

[params]
  env = "production"
  description = "- - -"
  author = "O R P H I C"
  
  defaultTheme = "dark"
  disableThemeToggle = true
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true

[menu]
  [[menu.main]]
    name = "A R T I C L E S"
    url = "/posts/"
    weight = 10
  
  [[menu.main]]
    name = "C A T E G O R I E S"
    url = "/categories/"
    weight = 20

  [[menu.main]]
    name = "T A G S"
    url = "/tags/"
    weight = 30
  
  [[menu.main]]
    name = "A B O U T"
    url = "/about/"
    weight = 40

[outputs]
  home = ["HTML", "RSS", "JSON"]
